# Generated by Django 3.0.4 on 2020-05-07 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_M_MateriaPrima',
            fields=[
                ('IDProducto', models.CharField(help_text='Ingrese su Clave de Producto', max_length=30, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=150)),
                ('IDFoto', models.ImageField(max_length=110, null=True, upload_to='Pictures')),
                ('FechaAlta', models.DateTimeField(default=django.utils.timezone.now)),
                ('UnidadMedida', models.CharField(max_length=10)),
                ('ExistenciaActual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
            ],
        ),
    ]
