# Generated by Django 3.0.4 on 2020-05-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_m_proveedor',
            old_name='Telefono3',
            new_name='Telefono2',
        ),
    ]
