# Generated by Django 3.0.4 on 2020-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cat_m_inventario_tbl_m_movtosinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='IDProducto',
            field=models.CharField(choices=[('PRODCUCTO TERMINADO', 'PRODCUCTO TERMINADO'), ('MATERIA PRIMA', 'MATERIA PRIMA'), ('MATERIAL EN PROCESO', 'MATERIAL EN PROCESO')], help_text='Ingrese su Clave de Producto', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='Status',
            field=models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('DESCONTINUADO', 'DESCONTINUADO'), ('CANCELADO', 'CANCELADO'), ('SUSPENDIDO', 'SUSPENDIDO')], default='VIGENTE', max_length=20),
        ),
    ]
