# Generated by Django 3.0.4 on 2020-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_auto_20200514_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='IDProducto',
            field=models.CharField(help_text='Ingrese su Clave de Producto', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='IDTipoProducto',
            field=models.CharField(choices=[('PRODCUCTO TERMINADO', 'PRODCUCTO TERMINADO'), ('MATERIA PRIMA', 'MATERIA PRIMA'), ('MATERIAL EN PROCESO', 'MATERIAL EN PROCESO')], default='PRODUCTO TERMINADO', max_length=30),
        ),
    ]
