# Generated by Django 3.0.4 on 2020-05-15 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_auto_20200515_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_M_Clientes',
            fields=[
                ('IDCliente', models.CharField(help_text='Ingrese Clave de Cliente', max_length=30, primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(max_length=150)),
                ('NombreProveedor', models.CharField(max_length=150)),
                ('Empresa', models.CharField(max_length=50)),
                ('Rfc', models.CharField(max_length=150)),
                ('DirFiscal', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(max_length=50)),
                ('Telefono3', models.CharField(max_length=50)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlFecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_M_Proveedores',
            fields=[
                ('IDProveedor', models.CharField(help_text='Ingrese Clave de Proveedor', max_length=30, primary_key=True, serialize=False)),
                ('NombreProveedor', models.CharField(max_length=150)),
                ('Empresa', models.CharField(max_length=50)),
                ('Rfc', models.CharField(max_length=150)),
                ('DirFiscal', models.CharField(max_length=150)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(max_length=50)),
                ('Telefono3', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_D_ProveedoresContactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreContacto', models.CharField(max_length=100)),
                ('CargoContacto', models.CharField(max_length=50)),
                ('SucursalContacto', models.CharField(max_length=50)),
                ('DireccionContacto', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(max_length=50)),
                ('Telefono3', models.CharField(max_length=50)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDProveedor', models.ForeignKey(help_text='Ingrese Clave de Proveedor', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Cat_D_ClientesSucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreContacto', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=50)),
                ('Sucursal', models.CharField(max_length=50)),
                ('Direccion', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(max_length=50)),
                ('Telefono3', models.CharField(max_length=50)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCliente', models.ForeignKey(help_text='Ingrese Clave de Cliente', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Clientes')),
            ],
        ),
    ]
