# Generated by Django 3.0.4 on 2020-05-16 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_cat_d_clientessucursales_cat_d_proveedorescontactos_cat_m_clientes_cat_m_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_M_CajaBanco',
            fields=[
                ('IDCajaBanco', models.CharField(help_text='Ingrese Clave Caja/Banco', max_length=30, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Sucursal', models.CharField(blank=True, max_length=50)),
                ('Direccion', models.CharField(blank=True, max_length=100)),
                ('Num_CLABE', models.CharField(blank=True, max_length=30)),
                ('Num_Cuenta', models.CharField(blank=True, max_length=30)),
                ('Titular', models.CharField(blank=True, max_length=30)),
                ('TipoCuenta', models.CharField(blank=True, max_length=30)),
                ('NomBanco', models.CharField(blank=True, max_length=30)),
                ('Ejecutivo', models.CharField(blank=True, max_length=50)),
                ('Telefono1', models.CharField(blank=True, max_length=50)),
                ('Telefono2', models.CharField(blank=True, max_length=50)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_M_Empleado',
            fields=[
                ('IDEmpleado', models.CharField(help_text='Ingrese Clave Prospecto', max_length=30, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Foto', models.ImageField(max_length=110, null=True, upload_to='Pictures')),
                ('Direccion', models.TextField()),
                ('Imss', models.CharField(max_length=30)),
                ('Rfc', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('PeriodoPago', models.IntegerField(blank=True, default=0, help_text='Periodo Pago (Dias)')),
                ('Sueldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('HorasExtra', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=20)),
                ('Area', models.CharField(max_length=30)),
                ('MontoHoraExtra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('Puesto', models.CharField(max_length=30)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_M_Vendedor',
            fields=[
                ('IDVendedor', models.CharField(help_text='Ingrese Clave de Vendedor', max_length=30, primary_key=True, serialize=False)),
                ('NombreVendedor', models.CharField(max_length=100)),
                ('Direccion', models.TextField()),
                ('Rfc', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(blank=True, max_length=50)),
                ('Telefono3', models.CharField(blank=True, max_length=50)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='cat_d_clientessucursales',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_d_clientessucursales',
            name='Telefono3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_d_proveedorescontactos',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_d_proveedorescontactos',
            name='Telefono3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='Empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='NombreCliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='NombreProveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='Rfc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_clientes',
            name='Telefono3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='CostoUnitarioultimaProducción',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='DiasPromedioResurtimiento',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='Preciocostoultimacompra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='Preciovtaultimaproduccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='Preciovtaunitarioultimaproduccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cat_m_inventario',
            name='Produccionmaxdia',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cat_m_proveedores',
            name='Empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat_m_proveedores',
            name='NombreProveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat_m_proveedores',
            name='Rfc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cat_m_proveedores',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_proveedores',
            name='Telefono3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Cat_M_Prospecto',
            fields=[
                ('IDProspecto', models.CharField(help_text='Ingrese Clave Prospecto', max_length=30, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('TipoCaptacion', models.CharField(choices=[('DIRECTO', 'DIRECTO'), ('VENDEDOR', 'VENDEDOR'), ('PAGINA_WEB', 'PAGINA_WEB'), ('OTROS', 'OTROS')], default='DIRECTO', max_length=30)),
                ('UsoMaterial', models.CharField(help_text='Para que necesita el material?', max_length=40)),
                ('Constructora', models.CharField(blank=True, help_text='Nombre Constructora', max_length=40, null=True)),
                ('CasaMateriales', models.CharField(blank=True, help_text='Nombre Casa Materiales', max_length=40, null=True)),
                ('ProductosInteres', models.TextField(help_text='Productos de Interes, Incluyendo Cantidades')),
                ('FechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Puesto', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('Telefono2', models.CharField(blank=True, max_length=50)),
                ('Telefono3', models.CharField(blank=True, max_length=50)),
                ('Direccion', models.TextField()),
                ('Estatus', models.CharField(choices=[('VIGENTE', 'SI'), ('CANCELADO', 'NO'), ('ALTA_CLIENTE', 'ALTA_CLIENTE')], default='VIGENTE', max_length=20)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('NombreVendedor', models.ForeignKey(blank=True, help_text='Ingrese Vendedor', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cat_M_Flete',
            fields=[
                ('IDFlete', models.CharField(help_text='Ingrese Clave Flete', max_length=30, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('CapacidadMinimaTarimas', models.IntegerField(blank=True, default=0)),
                ('CapacidadMaximaTarimas', models.IntegerField(blank=True, default=0)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('KilometrosMaxDistancia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('NombreProveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Cat_D_Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaNota', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProximoSeguimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('Seguimiento', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDProspecto', models.ForeignKey(blank=True, help_text='Ingrese ID Prospecto', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Vendedor')),
            ],
        ),
    ]
