# Generated by Django 3.0.4 on 2020-05-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20200516_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_m_empleado',
            old_name='Imss',
            new_name='NSS',
        ),
    ]
