# Generated by Django 3.0.4 on 2020-05-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_auto_20200516_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat_M_MateriaPrima',
        ),
    ]
