# Generated by Django 3.0.4 on 2020-05-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_delete_cat_m_materiaprima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_m_prospecto',
            name='NombreVendedor',
            field=models.ForeignKey(help_text='Ingrese Vendedor', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Vendedor'),
        ),
    ]
