# Generated by Django 3.0.4 on 2020-05-21 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_auto_20200520_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_D_ClienteSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreContacto', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=50)),
                ('Sucursal', models.CharField(max_length=50)),
                ('Direccion', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('WhatsApp', models.CharField(blank=True, max_length=50)),
                ('Telefono2', models.CharField(blank=True, max_length=50)),
                ('Comentarios', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_M_Cliente',
            fields=[
                ('IDCliente', models.CharField(help_text='Ingrese Clave de Cliente', max_length=30, primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(max_length=100)),
                ('Empresa', models.CharField(max_length=100)),
                ('Rfc', models.CharField(max_length=30)),
                ('DirFiscal', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono1', models.CharField(max_length=50)),
                ('WhatsApp', models.CharField(blank=True, max_length=50)),
                ('Telefono2', models.CharField(blank=True, max_length=50)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlFecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cat_D_ProveedoresContactos',
            new_name='Cat_D_ProveedorContacto',
        ),
        migrations.RenameModel(
            old_name='Cat_M_Proveedores',
            new_name='Cat_M_Proveedor',
        ),
        migrations.RemoveField(
            model_name='cat_d_clientessucursales',
            name='IDCliente',
        ),
        migrations.DeleteModel(
            name='Tbl_M_MovtosInventario',
        ),
        migrations.RenameField(
            model_name='cat_d_proveedorcontacto',
            old_name='Telefono3',
            new_name='WhatsApp',
        ),
        migrations.RenameField(
            model_name='cat_m_cajabanco',
            old_name='Nombre',
            new_name='NombreCajaBanco',
        ),
        migrations.RenameField(
            model_name='cat_m_empleado',
            old_name='Nombre',
            new_name='NombreEmpleado',
        ),
        migrations.RenameField(
            model_name='cat_m_flete',
            old_name='Nombre',
            new_name='NombreFlete',
        ),
        migrations.RenameField(
            model_name='cat_m_inventario',
            old_name='Status',
            new_name='Estatus',
        ),
        migrations.RenameField(
            model_name='cat_m_prospecto',
            old_name='Nombre',
            new_name='NombreProspecto',
        ),
        migrations.RenameField(
            model_name='cat_m_prospecto',
            old_name='Telefono3',
            new_name='WhatsApp',
        ),
        migrations.RenameField(
            model_name='cat_m_proveedor',
            old_name='Telefono2',
            new_name='WhatsApp',
        ),
        migrations.RemoveField(
            model_name='cat_d_prospecto',
            name='IDProspecto',
        ),
        migrations.RemoveField(
            model_name='cat_d_prospecto',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='cat_m_vendedor',
            name='Telefono3',
        ),
        migrations.AddField(
            model_name='cat_d_prospecto',
            name='Prospecto',
            field=models.ForeignKey(blank=True, default=0, help_text='Ingrese Prospecto', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Prospecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat_m_vendedor',
            name='WhatsApp',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_prospecto',
            name='Estatus',
            field=models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('CANCELADO', 'CANCELADO'), ('ALTA_CLIENTE', 'ALTA_CLIENTE')], default='VIGENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cat_m_prospecto',
            name='NombreVendedor',
            field=models.ForeignKey(blank=True, help_text='Ingrese Vendedor', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Vendedor'),
        ),
        migrations.AlterField(
            model_name='cat_m_vendedor',
            name='NombreVendedor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cat_m_vendedor',
            name='Telefono1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cat_m_vendedor',
            name='Telefono2',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.DeleteModel(
            name='Cat_D_ClientesSucursales',
        ),
        migrations.DeleteModel(
            name='Cat_M_Clientes',
        ),
        migrations.AddField(
            model_name='cat_m_cliente',
            name='NombreVendedor',
            field=models.ForeignKey(help_text='Seleccione Vendedor', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Vendedor'),
        ),
        migrations.AddField(
            model_name='cat_d_clientesucursal',
            name='IDCliente',
            field=models.ForeignKey(help_text='Ingrese Cliente', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Cliente'),
        ),
    ]
