# Generated by Django 3.0.4 on 2020-06-13 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_M_MovtosInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDMovimiento', models.IntegerField(help_text='Consecutivo numerico')),
                ('IDPeriodo', models.IntegerField(choices=[('052020', '052020'), ('062020', '062020'), ('072020', '072020'), ('072020', '072020'), ('072020', '072020'), ('072020', '072020'), ('072020', '072020'), ('072020', '072020')])),
                ('IDPlanProducción', models.CharField(help_text='Ingrese su Clave dePlan produccion recomendacion ddmmaa', max_length=30)),
                ('IDVenta', models.IntegerField(help_text='Consecutivo del maestro de ventas')),
                ('IDCompra', models.IntegerField(help_text='Consecutivo del maestro de compras')),
                ('IDTipoMovimiento', models.IntegerField(help_text='SOLO ELIGE TIPO MOVIMIENTO')),
                ('FechaMovto', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2)),
                ('Observaciones', models.CharField(max_length=150)),
                ('IdEmpleado', models.CharField(max_length=30)),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('NombreProducto', models.ForeignKey(help_text='Ingrese Nombre Producto', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_M_Formula',
            fields=[
                ('IDFormula', models.CharField(help_text='Ingrese su Clave de Formula', max_length=30, primary_key=True, serialize=False)),
                ('NumeroPiezas', models.IntegerField()),
                ('NombreResponsable', models.CharField(help_text='Ingrese Nombre Responsable', max_length=30)),
                ('EstatusFormula', models.IntegerField(choices=[('CANCELADO', 'CANCELADO'), ('EN PROCESO', 'EN PROCESO'), ('VIGENTE', 'VIGENTE')])),
                ('FechaLiberacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('kilosMermaAprox', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('Observaciones', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('NombreProducto', models.ForeignKey(help_text='Ingrese Nombre Producto', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_D_Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('NombreResponsable', models.CharField(help_text='Ingrese Nombre Responsable', max_length=30)),
                ('FechaLiberacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('kilosMermaAprox', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('Observaciones', models.TextField()),
                ('ctlusuario', models.CharField(max_length=30)),
                ('ctlfecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDFormula', models.ForeignKey(help_text='Ingrese Id de Formula', on_delete=django.db.models.deletion.CASCADE, to='inventarios.Tbl_M_Formula')),
                ('NombreProducto', models.ForeignKey(help_text='Ingrese Nombre Producto', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Cat_M_Inventario')),
            ],
        ),
    ]
